# Site settings
title: Scrimp
description: >- # this means to ignore newlines until "baseurl:"
  A Gradle plugin designed to only run tests when your code actually changes.
baseurl: "/scrimp"
url: "https://vaughandroid.me"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed

# Just the Docs theme settings
search_enabled: false # Need to set up GitHub Actions to get this to work.
aux_links:
  "View Scrimp on GitHub":
    - "https://github.com/vaughandroid/scrimp"

exclude:
  - README.md
